"""Description of the migration

Revision ID: 0dbf9e79f16d
Revises: ffcd183ab256
Create Date: 2025-04-08 14:00:30.416039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbf9e79f16d'
down_revision = 'ffcd183ab256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fido_info', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fido_info')

    # ### end Alembic commands ###
