"""address updates ver 2

Revision ID: 150a33cd90c7
Revises: 9aedf8cd5f19
Create Date: 2025-05-01 00:54:58.937693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150a33cd90c7'
down_revision = '9aedf8cd5f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'refbrgy', ['brgy'], ['brgyCode'])
        batch_op.create_foreign_key(None, 'refcitymun', ['citymun'], ['citymunCode'])
        batch_op.create_foreign_key(None, 'refregion', ['region'], ['regCode'])
        batch_op.create_foreign_key(None, 'refprovince', ['province'], ['provCode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
