"""Update FIDO-INFO in USer table

Revision ID: 6f3ba759f7a0
Revises: 0dbf9e79f16d
Create Date: 2025-04-08 14:24:43.234121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f3ba759f7a0'
down_revision = '0dbf9e79f16d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fido_info',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fido_info',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
