"""Initial migration

Revision ID: 70bc185d8b33
Revises: 
Create Date: 2025-04-07 19:05:28.880231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70bc185d8b33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', 'CLIENT', name='userrole'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('birthplace', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('MOTHER', 'FATHER', name='parentrole'), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('church', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='prieststatus'), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('ligitivity', sa.Enum('CIVIL', 'CATHOLIC', name='ligitivity'), nullable=True),
    sa.Column('birthplace', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('SINGLE', 'MARRIED', 'WIDOWED', 'SEPARATED', name='civilstatus'), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.Column('father_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['father_id'], ['parent.id'], ),
    sa.ForeignKeyConstraint(['mother_id'], ['parent.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baptism',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baptism_date', sa.Date(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('sponsorA', sa.String(length=255), nullable=False),
    sa.Column('residenceA', sa.String(length=255), nullable=False),
    sa.Column('sponsorB', sa.String(length=255), nullable=False),
    sa.Column('residenceB', sa.String(length=255), nullable=False),
    sa.Column('priest_id', sa.Integer(), nullable=False),
    sa.Column('rec_index', sa.String(length=255), nullable=False),
    sa.Column('rec_book', sa.String(length=255), nullable=False),
    sa.Column('rec_page', sa.Integer(), nullable=False),
    sa.Column('rec_line', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['priest_id'], ['priest.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confirmation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirmation_date', sa.Date(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('church_baptized', sa.String(length=255), nullable=False),
    sa.Column('sponsorA', sa.String(length=255), nullable=False),
    sa.Column('sponsorB', sa.String(length=255), nullable=False),
    sa.Column('priest_id', sa.Integer(), nullable=False),
    sa.Column('rec_index', sa.String(length=255), nullable=False),
    sa.Column('rec_book', sa.String(length=255), nullable=False),
    sa.Column('rec_page', sa.Integer(), nullable=False),
    sa.Column('rec_line', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['priest_id'], ['priest.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('death',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('death_date', sa.Date(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('burial_date', sa.Date(), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=False),
    sa.Column('cp_address', sa.String(length=255), nullable=False),
    sa.Column('cause_of_death', sa.String(length=255), nullable=False),
    sa.Column('burial_place', sa.String(length=255), nullable=False),
    sa.Column('priest_id', sa.Integer(), nullable=False),
    sa.Column('rec_index', sa.String(length=255), nullable=False),
    sa.Column('rec_book', sa.String(length=255), nullable=False),
    sa.Column('rec_page', sa.Integer(), nullable=False),
    sa.Column('rec_line', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['priest_id'], ['priest.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wedding_date', sa.Date(), nullable=False),
    sa.Column('groom_record_id', sa.Integer(), nullable=False),
    sa.Column('bride_record_id', sa.Integer(), nullable=False),
    sa.Column('sponsorA', sa.String(length=255), nullable=False),
    sa.Column('sponsorB', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=255), nullable=False),
    sa.Column('civil_date', sa.Date(), nullable=False),
    sa.Column('civil_place', sa.String(length=255), nullable=False),
    sa.Column('priest_id', sa.Integer(), nullable=False),
    sa.Column('rec_index', sa.String(length=255), nullable=False),
    sa.Column('rec_book', sa.String(length=255), nullable=False),
    sa.Column('rec_page', sa.Integer(), nullable=False),
    sa.Column('rec_line', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bride_record_id'], ['record.id'], ),
    sa.ForeignKeyConstraint(['groom_record_id'], ['record.id'], ),
    sa.ForeignKeyConstraint(['priest_id'], ['priest.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wedding')
    op.drop_table('death')
    op.drop_table('confirmation')
    op.drop_table('baptism')
    op.drop_table('record')
    op.drop_table('priest')
    op.drop_table('parent')
    op.drop_table('user')
    # ### end Alembic commands ###
