"""REtract Latest Update

Revision ID: 9aedf8cd5f19
Revises: f51c0c682963
Create Date: 2025-04-30 23:26:35.610248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9aedf8cd5f19'
down_revision = 'f51c0c682963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refbrgy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('brgyCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('refcitymun', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('citymunCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('refprovince', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('provCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('refregion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('regCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refregion', schema=None) as batch_op:
        batch_op.alter_column('regCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('id')

    with op.batch_alter_table('refprovince', schema=None) as batch_op:
        batch_op.alter_column('provCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('id')

    with op.batch_alter_table('refcitymun', schema=None) as batch_op:
        batch_op.alter_column('citymunCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('id')

    with op.batch_alter_table('refbrgy', schema=None) as batch_op:
        batch_op.alter_column('brgyCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
