"""Double Check Update

Revision ID: f51c0c682963
Revises: 6f3ba759f7a0
Create Date: 2025-04-30 19:57:51.566205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f51c0c682963'
down_revision = '6f3ba759f7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refbrgy', schema=None) as batch_op:
        batch_op.alter_column('brgyCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('brgyDesc',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('regCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('provCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('citymunCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_index('brgyCode')

    with op.batch_alter_table('refcitymun', schema=None) as batch_op:
        batch_op.drop_index('citymunCode')
        batch_op.drop_index('citymunCode_2')

    with op.batch_alter_table('refprovince', schema=None) as batch_op:
        batch_op.drop_index('provCode')
        batch_op.drop_index('provCode_2')
        batch_op.drop_index('provCode_3')

    with op.batch_alter_table('refregion', schema=None) as batch_op:
        batch_op.alter_column('regCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_index('regCode')
        batch_op.drop_index('regCode_2')
        batch_op.drop_index('regCode_3')
        batch_op.drop_index('regCode_4')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refregion', schema=None) as batch_op:
        batch_op.create_index('regCode_4', ['regCode'], unique=True)
        batch_op.create_index('regCode_3', ['regCode'], unique=True)
        batch_op.create_index('regCode_2', ['regCode'], unique=True)
        batch_op.create_index('regCode', ['regCode'], unique=True)
        batch_op.alter_column('regCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('refprovince', schema=None) as batch_op:
        batch_op.create_index('provCode_3', ['provCode'], unique=True)
        batch_op.create_index('provCode_2', ['provCode'], unique=True)
        batch_op.create_index('provCode', ['provCode'], unique=True)

    with op.batch_alter_table('refcitymun', schema=None) as batch_op:
        batch_op.create_index('citymunCode_2', ['citymunCode'], unique=True)
        batch_op.create_index('citymunCode', ['citymunCode'], unique=True)

    with op.batch_alter_table('refbrgy', schema=None) as batch_op:
        batch_op.create_index('brgyCode', ['brgyCode'], unique=True)
        batch_op.alter_column('citymunCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('provCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('regCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('brgyDesc',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('brgyCode',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
