"""Description of the migration

Revision ID: ffcd183ab256
Revises: 70bc185d8b33
Create Date: 2025-04-08 00:10:03.221395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffcd183ab256'
down_revision = '70bc185d8b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('birthplace',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('MOTHER', 'FATHER'),
               nullable=False)

    with op.batch_alter_table('priest', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('position',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('church',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('ACTIVE', 'INACTIVE'),
               nullable=False)

    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('ligitivity',
               existing_type=mysql.ENUM('CIVIL', 'CATHOLIC'),
               nullable=False)
        batch_op.alter_column('birthplace',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('SINGLE', 'MARRIED', 'WIDOWED', 'SEPARATED'),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('mother_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('father_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('contact_number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'STAFF', 'CLIENT'),
               nullable=False)
        batch_op.drop_index('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'STAFF', 'CLIENT'),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('contact_number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.alter_column('father_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('mother_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('SINGLE', 'MARRIED', 'WIDOWED', 'SEPARATED'),
               nullable=True)
        batch_op.alter_column('birthplace',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('ligitivity',
               existing_type=mysql.ENUM('CIVIL', 'CATHOLIC'),
               nullable=True)
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('priest', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('ACTIVE', 'INACTIVE'),
               nullable=True)
        batch_op.alter_column('church',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('position',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('MOTHER', 'FATHER'),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('birthplace',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('birthday',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
